# Generated by Django 3.1.6 on 2021-02-10 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(default='pics/default-post-pic.png', upload_to='pics'),
        ),
    ]
